/*
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.46.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.AuthServiceExpireSelfRequest;
import org.openapitools.client.model.Authentication;
import org.openapitools.client.model.AuthenticationList;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthServiceApi
 */
@Disabled
public class AuthServiceApiTest {

    private final AuthServiceApi api = new AuthServiceApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void authServiceDeleteTokenTest() throws ApiException {
        String id = null;
        api.authServiceDeleteToken(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void authServiceExpireSelfTest() throws ApiException {
        AuthServiceExpireSelfRequest authServiceExpireSelfRequest = null;
        api.authServiceExpireSelf(authServiceExpireSelfRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void authServiceGetSelfTest() throws ApiException {
        Authentication response = api.authServiceGetSelf();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void authServiceGetTokenTest() throws ApiException {
        String id = null;
        Authentication response = api.authServiceGetToken(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void authServiceListTokensTest() throws ApiException {
        AuthenticationList response = api.authServiceListTokens();
        // TODO: test validations
    }

}
