/*
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.46.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.AuthMethodK8SServiceVerifyServiceAccountRequest;
import org.openapitools.client.model.AuthenticationToken;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthMethodK8SServiceApi
 */
@Disabled
public class AuthMethodK8SServiceApiTest {

    private final AuthMethodK8SServiceApi api = new AuthMethodK8SServiceApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void authMethodK8SServiceVerifyServiceAccountTest() throws ApiException {
        AuthMethodK8SServiceVerifyServiceAccountRequest authMethodK8SServiceVerifyServiceAccountRequest = null;
        AuthenticationToken response = api.authMethodK8SServiceVerifyServiceAccount(authMethodK8SServiceVerifyServiceAccountRequest);
        // TODO: test validations
    }

}
