/*
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.46.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Constraint;
import org.openapitools.client.model.ConstraintCreateRequest;
import org.openapitools.client.model.ConstraintUpdateRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConstraintsServiceApi
 */
@Disabled
public class ConstraintsServiceApiTest {

    private final ConstraintsServiceApi api = new ConstraintsServiceApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void constraintsServiceCreateTest() throws ApiException {
        String namespaceKey = null;
        String segmentKey = null;
        ConstraintCreateRequest constraintCreateRequest = null;
        Constraint response = api.constraintsServiceCreate(namespaceKey, segmentKey, constraintCreateRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void constraintsServiceDeleteTest() throws ApiException {
        String namespaceKey = null;
        String segmentKey = null;
        String id = null;
        api.constraintsServiceDelete(namespaceKey, segmentKey, id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void constraintsServiceUpdateTest() throws ApiException {
        String namespaceKey = null;
        String segmentKey = null;
        String id = null;
        ConstraintUpdateRequest constraintUpdateRequest = null;
        api.constraintsServiceUpdate(namespaceKey, segmentKey, id, constraintUpdateRequest);
        // TODO: test validations
    }

}
