/*
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.46.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Namespace;
import org.openapitools.client.model.NamespaceCreateRequest;
import org.openapitools.client.model.NamespaceList;
import org.openapitools.client.model.NamespaceUpdateRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NamespacesServiceApi
 */
@Disabled
public class NamespacesServiceApiTest {

    private final NamespacesServiceApi api = new NamespacesServiceApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void namespacesServiceCreateTest() throws ApiException {
        NamespaceCreateRequest namespaceCreateRequest = null;
        Namespace response = api.namespacesServiceCreate(namespaceCreateRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void namespacesServiceDeleteTest() throws ApiException {
        String key = null;
        api.namespacesServiceDelete(key);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void namespacesServiceGetTest() throws ApiException {
        String key = null;
        String reference = null;
        Namespace response = api.namespacesServiceGet(key, reference);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void namespacesServiceListTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        String pageToken = null;
        String reference = null;
        NamespaceList response = api.namespacesServiceList(limit, offset, pageToken, reference);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void namespacesServiceUpdateTest() throws ApiException {
        String key = null;
        NamespaceUpdateRequest namespaceUpdateRequest = null;
        Namespace response = api.namespacesServiceUpdate(key, namespaceUpdateRequest);
        // TODO: test validations
    }

}
