/*
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.46.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Segment;
import org.openapitools.client.model.SegmentCreateRequest;
import org.openapitools.client.model.SegmentList;
import org.openapitools.client.model.SegmentUpdateRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SegmentsServiceApi
 */
@Disabled
public class SegmentsServiceApiTest {

    private final SegmentsServiceApi api = new SegmentsServiceApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void segmentsServiceCreateTest() throws ApiException {
        String namespaceKey = null;
        SegmentCreateRequest segmentCreateRequest = null;
        Segment response = api.segmentsServiceCreate(namespaceKey, segmentCreateRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void segmentsServiceDeleteTest() throws ApiException {
        String namespaceKey = null;
        String key = null;
        api.segmentsServiceDelete(namespaceKey, key);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void segmentsServiceGetTest() throws ApiException {
        String namespaceKey = null;
        String key = null;
        String reference = null;
        Segment response = api.segmentsServiceGet(namespaceKey, key, reference);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void segmentsServiceListTest() throws ApiException {
        String namespaceKey = null;
        Integer limit = null;
        Integer offset = null;
        String pageToken = null;
        String reference = null;
        SegmentList response = api.segmentsServiceList(namespaceKey, limit, offset, pageToken, reference);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void segmentsServiceUpdateTest() throws ApiException {
        String namespaceKey = null;
        String key = null;
        SegmentUpdateRequest segmentUpdateRequest = null;
        Segment response = api.segmentsServiceUpdate(namespaceKey, key, segmentUpdateRequest);
        // TODO: test validations
    }

}
