/*
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.46.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Variant;
import org.openapitools.client.model.VariantCreateRequest;
import org.openapitools.client.model.VariantUpdateRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VariantsServiceApi
 */
@Disabled
public class VariantsServiceApiTest {

    private final VariantsServiceApi api = new VariantsServiceApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void variantsServiceCreateTest() throws ApiException {
        String namespaceKey = null;
        String flagKey = null;
        VariantCreateRequest variantCreateRequest = null;
        Variant response = api.variantsServiceCreate(namespaceKey, flagKey, variantCreateRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void variantsServiceDeleteTest() throws ApiException {
        String namespaceKey = null;
        String flagKey = null;
        String id = null;
        api.variantsServiceDelete(namespaceKey, flagKey, id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void variantsServiceUpdateTest() throws ApiException {
        String namespaceKey = null;
        String flagKey = null;
        String id = null;
        VariantUpdateRequest variantUpdateRequest = null;
        Variant response = api.variantsServiceUpdate(namespaceKey, flagKey, id, variantUpdateRequest);
        // TODO: test validations
    }

}
