/*
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.46.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The default is METHOD_NONE
 */
@JsonAdapter(AuthenticationMethod.Adapter.class)
public enum AuthenticationMethod {
  
  NONE("METHOD_NONE"),
  
  TOKEN("METHOD_TOKEN"),
  
  OIDC("METHOD_OIDC"),
  
  KUBERNETES("METHOD_KUBERNETES"),
  
  JWT("METHOD_JWT");

  private String value;

  AuthenticationMethod(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AuthenticationMethod fromValue(String value) {
    for (AuthenticationMethod b : AuthenticationMethod.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<AuthenticationMethod> {
    @Override
    public void write(final JsonWriter jsonWriter, final AuthenticationMethod enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AuthenticationMethod read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AuthenticationMethod.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    AuthenticationMethod.fromValue(value);
  }
}

