/*
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.46.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets EvaluationReason
 */
@JsonAdapter(EvaluationReason.Adapter.class)
public enum EvaluationReason {
  
  UNKNOWN_EVALUATION_REASON("UNKNOWN_EVALUATION_REASON"),
  
  FLAG_DISABLED_EVALUATION_REASON("FLAG_DISABLED_EVALUATION_REASON"),
  
  MATCH_EVALUATION_REASON("MATCH_EVALUATION_REASON"),
  
  DEFAULT_EVALUATION_REASON("DEFAULT_EVALUATION_REASON");

  private String value;

  EvaluationReason(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EvaluationReason fromValue(String value) {
    for (EvaluationReason b : EvaluationReason.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<EvaluationReason> {
    @Override
    public void write(final JsonWriter jsonWriter, final EvaluationReason enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EvaluationReason read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EvaluationReason.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    EvaluationReason.fromValue(value);
  }
}

