/*
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.46.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.BooleanEvaluationResponse;
import org.openapitools.client.model.ErrorEvaluationResponse;
import org.openapitools.client.model.EvaluationResponseType;
import org.openapitools.client.model.VariantEvaluationResponse;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * EvaluationResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-31T13:29:42.404334+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.9.0")
public class EvaluationResponse {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private EvaluationResponseType type;

  public static final String SERIALIZED_NAME_BOOLEAN_RESPONSE = "booleanResponse";
  @SerializedName(SERIALIZED_NAME_BOOLEAN_RESPONSE)
  private BooleanEvaluationResponse booleanResponse;

  public static final String SERIALIZED_NAME_VARIANT_RESPONSE = "variantResponse";
  @SerializedName(SERIALIZED_NAME_VARIANT_RESPONSE)
  private VariantEvaluationResponse variantResponse;

  public static final String SERIALIZED_NAME_ERROR_RESPONSE = "errorResponse";
  @SerializedName(SERIALIZED_NAME_ERROR_RESPONSE)
  private ErrorEvaluationResponse errorResponse;

  public EvaluationResponse() {
  }

  public EvaluationResponse type(EvaluationResponseType type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  public EvaluationResponseType getType() {
    return type;
  }

  public void setType(EvaluationResponseType type) {
    this.type = type;
  }


  public EvaluationResponse booleanResponse(BooleanEvaluationResponse booleanResponse) {
    this.booleanResponse = booleanResponse;
    return this;
  }

  /**
   * Get booleanResponse
   * @return booleanResponse
   */
  @javax.annotation.Nullable
  public BooleanEvaluationResponse getBooleanResponse() {
    return booleanResponse;
  }

  public void setBooleanResponse(BooleanEvaluationResponse booleanResponse) {
    this.booleanResponse = booleanResponse;
  }


  public EvaluationResponse variantResponse(VariantEvaluationResponse variantResponse) {
    this.variantResponse = variantResponse;
    return this;
  }

  /**
   * Get variantResponse
   * @return variantResponse
   */
  @javax.annotation.Nullable
  public VariantEvaluationResponse getVariantResponse() {
    return variantResponse;
  }

  public void setVariantResponse(VariantEvaluationResponse variantResponse) {
    this.variantResponse = variantResponse;
  }


  public EvaluationResponse errorResponse(ErrorEvaluationResponse errorResponse) {
    this.errorResponse = errorResponse;
    return this;
  }

  /**
   * Get errorResponse
   * @return errorResponse
   */
  @javax.annotation.Nullable
  public ErrorEvaluationResponse getErrorResponse() {
    return errorResponse;
  }

  public void setErrorResponse(ErrorEvaluationResponse errorResponse) {
    this.errorResponse = errorResponse;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvaluationResponse evaluationResponse = (EvaluationResponse) o;
    return Objects.equals(this.type, evaluationResponse.type) &&
        Objects.equals(this.booleanResponse, evaluationResponse.booleanResponse) &&
        Objects.equals(this.variantResponse, evaluationResponse.variantResponse) &&
        Objects.equals(this.errorResponse, evaluationResponse.errorResponse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, booleanResponse, variantResponse, errorResponse);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvaluationResponse {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    booleanResponse: ").append(toIndentedString(booleanResponse)).append("\n");
    sb.append("    variantResponse: ").append(toIndentedString(variantResponse)).append("\n");
    sb.append("    errorResponse: ").append(toIndentedString(errorResponse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("type");
    openapiFields.add("booleanResponse");
    openapiFields.add("variantResponse");
    openapiFields.add("errorResponse");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("type");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EvaluationResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EvaluationResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EvaluationResponse is not found in the empty JSON string", EvaluationResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EvaluationResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EvaluationResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : EvaluationResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `type`
      EvaluationResponseType.validateJsonElement(jsonObj.get("type"));
      // validate the optional field `booleanResponse`
      if (jsonObj.get("booleanResponse") != null && !jsonObj.get("booleanResponse").isJsonNull()) {
        BooleanEvaluationResponse.validateJsonElement(jsonObj.get("booleanResponse"));
      }
      // validate the optional field `variantResponse`
      if (jsonObj.get("variantResponse") != null && !jsonObj.get("variantResponse").isJsonNull()) {
        VariantEvaluationResponse.validateJsonElement(jsonObj.get("variantResponse"));
      }
      // validate the optional field `errorResponse`
      if (jsonObj.get("errorResponse") != null && !jsonObj.get("errorResponse").isJsonNull()) {
        ErrorEvaluationResponse.validateJsonElement(jsonObj.get("errorResponse"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EvaluationResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EvaluationResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EvaluationResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EvaluationResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<EvaluationResponse>() {
           @Override
           public void write(JsonWriter out, EvaluationResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EvaluationResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EvaluationResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EvaluationResponse
   * @throws IOException if the JSON string is invalid with respect to EvaluationResponse
   */
  public static EvaluationResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EvaluationResponse.class);
  }

  /**
   * Convert an instance of EvaluationResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

