/*
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.46.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets RolloutType
 */
@JsonAdapter(RolloutType.Adapter.class)
public enum RolloutType {
  
  UNKNOWN_ROLLOUT_TYPE("UNKNOWN_ROLLOUT_TYPE"),
  
  SEGMENT_ROLLOUT_TYPE("SEGMENT_ROLLOUT_TYPE"),
  
  THRESHOLD_ROLLOUT_TYPE("THRESHOLD_ROLLOUT_TYPE");

  private String value;

  RolloutType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static RolloutType fromValue(String value) {
    for (RolloutType b : RolloutType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<RolloutType> {
    @Override
    public void write(final JsonWriter jsonWriter, final RolloutType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public RolloutType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return RolloutType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    RolloutType.fromValue(value);
  }
}

