/*
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.46.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets RuleSegmentOperator
 */
@JsonAdapter(RuleSegmentOperator.Adapter.class)
public enum RuleSegmentOperator {
  
  OR_SEGMENT_OPERATOR("OR_SEGMENT_OPERATOR"),
  
  AND_SEGMENT_OPERATOR("AND_SEGMENT_OPERATOR");

  private String value;

  RuleSegmentOperator(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static RuleSegmentOperator fromValue(String value) {
    for (RuleSegmentOperator b : RuleSegmentOperator.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<RuleSegmentOperator> {
    @Override
    public void write(final JsonWriter jsonWriter, final RuleSegmentOperator enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public RuleSegmentOperator read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return RuleSegmentOperator.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    RuleSegmentOperator.fromValue(value);
  }
}

