/*
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.46.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Authentication;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AuthMethodOIDCCallbackResponse
 */
public class AuthMethodOIDCCallbackResponseTest {
    private final AuthMethodOIDCCallbackResponse model = new AuthMethodOIDCCallbackResponse();

    /**
     * Model tests for AuthMethodOIDCCallbackResponse
     */
    @Test
    public void testAuthMethodOIDCCallbackResponse() {
        // TODO: test AuthMethodOIDCCallbackResponse
    }

    /**
     * Test the property 'authentication'
     */
    @Test
    public void authenticationTest() {
        // TODO: test authentication
    }

}
