/*
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.46.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AuthMethodTokenServiceCreateTokenRequest
 */
public class AuthMethodTokenServiceCreateTokenRequestTest {
    private final AuthMethodTokenServiceCreateTokenRequest model = new AuthMethodTokenServiceCreateTokenRequest();

    /**
     * Model tests for AuthMethodTokenServiceCreateTokenRequest
     */
    @Test
    public void testAuthMethodTokenServiceCreateTokenRequest() {
        // TODO: test AuthMethodTokenServiceCreateTokenRequest
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'namespaceKey'
     */
    @Test
    public void namespaceKeyTest() {
        // TODO: test namespaceKey
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'expiresAt'
     */
    @Test
    public void expiresAtTest() {
        // TODO: test expiresAt
    }

}
