/*
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.46.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.EvaluationResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BatchEvaluationResponse
 */
public class BatchEvaluationResponseTest {
    private final BatchEvaluationResponse model = new BatchEvaluationResponse();

    /**
     * Model tests for BatchEvaluationResponse
     */
    @Test
    public void testBatchEvaluationResponse() {
        // TODO: test BatchEvaluationResponse
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    public void requestIdTest() {
        // TODO: test requestId
    }

    /**
     * Test the property 'responses'
     */
    @Test
    public void responsesTest() {
        // TODO: test responses
    }

    /**
     * Test the property 'requestDurationMillis'
     */
    @Test
    public void requestDurationMillisTest() {
        // TODO: test requestDurationMillis
    }

}
