/*
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.46.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.RolloutSegment;
import org.openapitools.client.model.RolloutThreshold;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RolloutUpdateRequest
 */
public class RolloutUpdateRequestTest {
    private final RolloutUpdateRequest model = new RolloutUpdateRequest();

    /**
     * Model tests for RolloutUpdateRequest
     */
    @Test
    public void testRolloutUpdateRequest() {
        // TODO: test RolloutUpdateRequest
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'segment'
     */
    @Test
    public void segmentTest() {
        // TODO: test segment
    }

    /**
     * Test the property 'threshold'
     */
    @Test
    public void thresholdTest() {
        // TODO: test threshold
    }

}
