/*
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.46.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.RolloutSegmentOperator;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RolloutSegment
 */
public class RolloutSegmentTest {
    private final RolloutSegment model = new RolloutSegment();

    /**
     * Model tests for RolloutSegment
     */
    @Test
    public void testRolloutSegment() {
        // TODO: test RolloutSegment
    }

    /**
     * Test the property 'segmentKey'
     */
    @Test
    public void segmentKeyTest() {
        // TODO: test segmentKey
    }

    /**
     * Test the property 'segmentKeys'
     */
    @Test
    public void segmentKeysTest() {
        // TODO: test segmentKeys
    }

    /**
     * Test the property 'segmentOperator'
     */
    @Test
    public void segmentOperatorTest() {
        // TODO: test segmentOperator
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
