/*
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.46.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Rollout;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RolloutList
 */
public class RolloutListTest {
    private final RolloutList model = new RolloutList();

    /**
     * Model tests for RolloutList
     */
    @Test
    public void testRolloutList() {
        // TODO: test RolloutList
    }

    /**
     * Test the property 'rollouts'
     */
    @Test
    public void rolloutsTest() {
        // TODO: test rollouts
    }

    /**
     * Test the property 'nextPageToken'
     */
    @Test
    public void nextPageTokenTest() {
        // TODO: test nextPageToken
    }

    /**
     * Test the property 'totalCount'
     */
    @Test
    public void totalCountTest() {
        // TODO: test totalCount
    }

}
