/*
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.46.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Distribution;
import org.openapitools.client.model.RuleSegmentOperator;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Rule
 */
public class RuleTest {
    private final Rule model = new Rule();

    /**
     * Model tests for Rule
     */
    @Test
    public void testRule() {
        // TODO: test Rule
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'namespaceKey'
     */
    @Test
    public void namespaceKeyTest() {
        // TODO: test namespaceKey
    }

    /**
     * Test the property 'flagKey'
     */
    @Test
    public void flagKeyTest() {
        // TODO: test flagKey
    }

    /**
     * Test the property 'segmentKey'
     */
    @Test
    public void segmentKeyTest() {
        // TODO: test segmentKey
    }

    /**
     * Test the property 'segmentKeys'
     */
    @Test
    public void segmentKeysTest() {
        // TODO: test segmentKeys
    }

    /**
     * Test the property 'segmentOperator'
     */
    @Test
    public void segmentOperatorTest() {
        // TODO: test segmentOperator
    }

    /**
     * Test the property 'distributions'
     */
    @Test
    public void distributionsTest() {
        // TODO: test distributions
    }

    /**
     * Test the property 'rank'
     */
    @Test
    public void rankTest() {
        // TODO: test rank
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
